---
development:
  cloud_name: dwse3ibga
  api_key: '694157367468922'
  api_secret: f_oXkmag5YnZn9l3Lhf5Alf0JEI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dwse3ibga
  api_key: '694157367468922'
  api_secret: f_oXkmag5YnZn9l3Lhf5Alf0JEI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dwse3ibga
  api_key: '694157367468922'
  api_secret: f_oXkmag5YnZn9l3Lhf5Alf0JEI
  enhance_image_tag: true
  static_file_support: false
